<a href="https://colab.research.google.com/github/Loveline-Ezenwafor/Analysis-by-Loveline-Ezenwafor/blob/Analysis%2FPython-Programming/JSON_reviews_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import json
import pandas as pd

In [73]:
file_path = '/content/data_10.json'
with open(file_path, 'r') as file:
    data = json.load(file)

In [74]:
reviews_data = []
count = 0
for result in data['results']:
  asin = result['content']["asin"]
  for review in result['content']['reviews']:
    count += 1
    try:
      review_info = {
      'review_id': review['id'],
      'product_id': asin,
      "title": review["title"],
      "author": review["author"],
      "rating": review["rating"],
      "content": review["content"],
      "timestamp": review["timestamp"],
      "profile_id": review["profile_id"],
      "is_verified": review["is_verified"],
      "helpful_count": review.get('helpful_count', 0),
      "product_attributes": review["product_attributes"]
      }
      reviews_data.append(review_info)
    except:
      print(count)
      break

reviews_df = pd.DataFrame(reviews_data)
reviews_df.to_csv('reviews_10.csv', index=False)
reviews_df

47
48
49
50
51
52

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R1VD1NFDXWX0BK,B0C8VDSBP6,"5.0 out of 5 stars Good, loud sound.",Rudy F. Garcia,5,"Good, loud sound. I use it for a percussive da...","Reviewed in the United States May 2, 2024",AETVL3GNYKYVAKG4SA2WJTFMF5LA,True,0,
1,R20K460EL7ILZH,B0C8VDSBP6,4.0 out of 5 stars Great sound lousy instructions,peganob19,4,"Like the sound and features, but nowhere in th...","Reviewed in the United States April 4, 2024",AESDGRGYSQ2CM5JDDBQIGRSJGTYQ,True,3,
2,R1JVD8814MAVCN,B0C8VDSBP6,5.0 out of 5 stars loud,Virginia Millan,5,yes it is loud or at least louder than the sto...,"Reviewed in the United States May 31, 2024",AGBZEPJC6ZQRUE5ZA4BUMFXMJOAA,True,0,
3,R5DOA58CCQ4I0,B0C8VDSBP6,1.0 out of 5 stars Horrible! 2 months and does...,Lawrence R. Weiner,1,Sound is ok when it worked. Battery life no wh...,"Reviewed in the United States May 7, 2024",AGBCR6T3S7O5MW27VFXI35OBCG6A,True,4,
4,R394ETPM5AZT4I,B0C8VDSBP6,5.0 out of 5 stars New update......,Dustin Sipes,5,A update!!!!!!!!! I was contacted by ortizan a...,"Reviewed in the United States May 20, 2024",AGMM2MYPAJEJJS4O2QEMXLOBLAAA,True,2,
5,RC21W6DHPQ20E,B0C8VDSBP6,3.0 out of 5 stars Disappointing compared to l...,Wilson Cheung,3,I was looking for 100W battery powered speaker...,"Reviewed in the United States October 31, 2023",AHMJJEDKK4SDHVN7FX3YV6HOBOXA,True,15,
6,RNFPEEAZEHBCC,B0C8VDSBP6,5.0 out of 5 stars RICH SOUND!,Carrolls,5,Decided to buy one and once I heard the clear ...,"Reviewed in the United States October 13, 2023",AGURI5JYEFGBPWYINI4LHQNW7VNA,True,6,
7,R1JV7JPP01UU6,B0C8VDSBP6,4.0 out of 5 stars Overall 1st experience,C Ramos,4,"This does have a exceptional sound, functions ...","Reviewed in the United States October 21, 2023",AEIZCENDEBIPKYEXLQMYM5KVSAAA,True,6,
8,RGCN1CFMQDRAR,B0C8VDSBP6,4.0 out of 5 stars Sound,Richard M.,4,A lot bigger and heavier than I expected. Was ...,"Reviewed in the United States October 15, 2023",AGTCMPFQJ6GC7EGNRW2YTXZ3S6IA,True,6,
9,R1YL99HIQ3XPAR,B0C8VDSBP6,5.0 out of 5 stars Amazing,Michael Arthur,5,,"Reviewed in the United States May 10, 2024",AFTBEGGL4P6BAIQTMY3ZFVOTBDPQ,True,0,
10,R2LZXFLV57FMR0,B0C8VDSBP6,5.0 out of 5 stars great sound,Robyn,5,So far so good. Great sound,"Reviewed in the United States April 24, 2024",AFAMDXQEH7ITKNVXASI2G7XWBFCA,True,0,
11,RIN748AVJV0FJ,B0C8VDSBP6,5.0 out of 5 stars The sound is amazing,Pierre Richard delima,5,I like everythingGood producy,"Reviewed in the United States April 1, 2024",AHNY5YCLQ26EMKQSRXS3XM3Y2EYQ,True,0,
12,RO976LRL9S2X2,B0C8VDSBP6,5.0 out of 5 stars Heavy,Cathy Valentine,5,"This is a great sounding speaker, but it is fa...","Reviewed in the United States February 2, 2024",AGVHLSE5N5NBO5MLB7JNXG4I7UBQ,True,3,
13,RDP7DV6623ESE,B0C8VDSBP6,5.0 out of 5 stars 3D & Lighting Fast Shipping,Amazon Customer,5,Item arrived before scheduled in nice packing....,"Reviewed in the United States October 12, 2023",AGYSYGFC53VYMCCTS4E255RKRM2A,True,3,
14,R13MH99WSRVM8N,B0C8VDSBP6,1.0 out of 5 stars Sub par low end.,Andy,1,I received this item expecting something that ...,"Reviewed in the United States April 8, 2024",AEARE3RAEBHCMTBGRAS64MEJU2ZQ,True,0,
15,R3251M4SJFG2FY,B0C8VDSBP6,2.0 out of 5 stars Not as loud as I would want...,Peggy Jobson,2,I actually thought that the sound would be a l...,"Reviewed in the United States November 25, 2023",AGF7JRRTPN5AKVL5UXX2UNBD3A3A,True,0,
16,R2D82QKKN91OVU,B0C8VDSBP6,5.0 out of 5 stars Very loud speaker,chris,5,"This speaker is very loud, clear and the light...","Reviewed in the United States May 6, 2023",AF7H5OMGHIOJANSGX2YWKSSZYVOQ,True,5,
17,R4G60CD17OTAZ,B0C8VDSBP6,1.0 out of 5 stars NOT 100 WATTS,Richard Davis,1,"This speaker is NOT 100 watts, I have a JBL sp...","Reviewed in the United States April 25, 2024",AFLMJT6YUGZK7SQAXZUNGHXWBCMQ,True,2,
18,R27VOQPV76PK9B,B0C8VDSBP6,5.0 out of 5 stars Ortizan rocks!,Rob H.,5,Awesome blue tooth speaker has great sound/bas...,"Reviewed in the United States May 2, 2021",AFL44FKGF6LPDVX6YJSG2TTQ724Q,True,8,
19,R1DN1WW6WHAHAV,B0C8VDSBP6,1.0 out of 5 stars Speaker does it's job but q...,Amber,1,4 days past the return window the charger cord...,"Reviewed in the United States May 12, 2024",AE4EEKXAJQZEV3LMEXVL4GW32B7A,True,0,
20,R1N2USF1ZRJ4ZV,B0C8VDSBP6,5.0 out of 5 stars great portable speaker,Robert,5,"i bought this because it is a nice size, and i...","Reviewed in the United States September 22, 2022",AGT7FISKHDWSUH4QTV7DKVPFIALA,True,3,
21,R1POOGY3A701OM,B0C8VDSBP6,5.0 out of 5 stars Epic,Keith,5,Use it at my restaurant and everyone loves it....,"Reviewed in the United States April 26, 2021",AHV6JSKMMQMIONTY5ENUILXDKDUA,True,14,
22,R1PE5Q1OMGYC19,B0C8VDSBP6,4.0 out of 5 stars Little lighted speaker,shonajoe,4,I was very with such a little speaker!,"Reviewed in the United States May 8, 2021",AE26D7VZFPZI4EPVKSSYQPHZ5WOA,True,1,
23,RZQCHLFMPDYEF,B0C8VDSBP6,3.0 out of 5 stars Doesn’t have good bass,Claudia Ramos,3,I noticed that this speaker doesn’t have a goo...,"Reviewed in the United States August 23, 2021",AHB72AFBMT2BWB4MFJCXOCLWLAMQ,True,5,
24,RAVCCEH1ET9JE,B0C8VDSBP6,2.0 out of 5 stars mediocre sound at best - re...,AnnieQ,2,Unfortunately I got too busy and missed return...,"Reviewed in the United States May 22, 2021",AEFSSOHJCOAYGN5A4QSQGMLSYH3Q,True,7,
25,R3LD2OU45CZZ26,B0C8VDSBP6,3.0 out of 5 stars Somewhat,Rowan,3,Okay,"Reviewed in the United States March 9, 2022",AEV3OM6GRPH434RSRS6BV2KDMNXQ,True,0,
26,R3FM5WI7C2ZNAQ,B0C8VDSBP6,5.0 out of 5 stars Compact size good sound,Danny Moncrief Jr,5,Very good for the money,"Reviewed in the United States March 31, 2022",AE3YFVRQLF34B64HEOR3ZDLO56LA,True,1,
27,R3CVFGWNDR0AIH,B0C8VDSBP6,5.0 out of 5 stars Sound quality,Patricia Drakeford,5,Sound quality is very good! Lights only on top...,"Reviewed in the United States July 10, 2021",AFTM6MAOG3LGUMXC5R2NSHA23MUA,True,1,
28,R369QV4IUON1EC,B0C8VDSBP6,1.0 out of 5 stars Don't buy,sara w,1,Don't buy. Sounds good. Lesa than a year charg...,"Reviewed in the United States February 17, 2023",AHHWQ2ONQNIKFBCRQJCU35YQLXBQ,True,3,
29,R1MUJFXLDAF9Y6,B0C8VDSBP6,4.0 out of 5 stars Almost 5 stars. (4.9) Excel...,Amazon Viewer,4,"It's a solid high-quality unit, and I almost g...","Reviewed in the United States April 6, 2024",AHL6PWXMS4JQYVB2SLVVZQUHNO6Q,False,0,
30,R2KQ0K2MGKAUH6,B0C8VDSBP6,4.0 out of 5 stars great value.,LJC,4,"Was really good at the beginning, after 2 mont...","Reviewed in the United States March 30, 2024",AHOGYLLFN5S4I2JMDY2HKX7WT72Q,False,0,
31,R21DO7EBBXEKG3,B0C8VDSBP6,2.0 out of 5 stars Poor sound,Maryanne Watson,2,Poor sound. Returned.,"Reviewed in the United States May 13, 2021",AGOYLFSJIQTVZE2TBHSY4R5U6STA,True,5,
32,R38X8H3NQHWWGJ,B0C8VDSBP6,4.0 out of 5 stars Good speaker with some issu...,Neointhematrix,4,Well made speaker. With a few caveats. First b...,"Reviewed in the United States January 22, 2024",AGOX6SXJ74WKBFGBKKZTR6PNOICA,False,2,
33,R29KGLTL58RV3B,B0C8VDSBP6,4.0 out of 5 stars it goes loud w/o distortion,Cee Vee,4,What i don't like is the e.q. & the multicolou...,"Reviewed in the United States December 12, 2023",AHMZ4PW5O7JOABCPZTZTDHODA4XA,False,1,
34,R22MEMNLRWE1IK,B0C8VDSBP6,4.0 out of 5 stars Good sound (depends on what...,hopeless,4,"For videos watching it’s good, music really de...","Reviewed in the United States January 9, 2024",AG4VNFZQHAYDAFR42PGBWU5DCEHA,False,1,
35,RUCS5NK27PUNE,B0C8VDSBP6,5.0 out of 5 stars Wow....just Wow!,Craig Witek,5,The media could not be loaded. Let me start ou...,"Reviewed in the United States August 31, 2023",AGEQANSOIGPED33645OIJXWOQ6TA,False,10,
36,R2MGVGZQAVQ98B,B0C8VDSBP6,5.0 out of 5 stars Faaantastic,greg,5,"Didn't need this sitting next to my Bose, Sana...","Reviewed in the United States August 15, 2023",AEJMFZ2ZXTES5GXUIMT4PSSF3L5A,False,2,
37,R36A2UCD69MWP7,B0C8VDSBP6,5.0 out of 5 stars An excellent sound,Josue Flores Anchondo,5,"I loved this product, I didn’t expect it to be...","Reviewed in the United States August 26, 2023",AEAGYHWDY4FIV4PSCF3GUJCPJBBQ,False,2,
38,R2FX0ZMEAIBJIW,B0C8VDSBP6,5.0 out of 5 stars Sounds great,LF,5,Looks and sounds great 👍Fair price 👌Would Buy ...,"Reviewed in the United States July 11, 2023",AHTQSVGCC3BEQPF4RC2DQXM3V5KQ,False,1,
39,RXWLSP57MARRG,B0C8VDSBP6,5.0 out of 5 stars Love it,Jessica grimm,5,It’s a good speaker and it have good volume,"Reviewed in the United States May 20, 2023",AHATI4WN6X7UMFDCRLYQ2HB6YXZQ,False,1,
40,R17JFNHNGLGPFQ,B0C8VDSBP6,5.0 out of 5 stars Loud,Ellisa G,5,This is a loud speaker for the price! It is po...,"Reviewed in the United States April 25, 2023",AFFMJEIJM3563DUSNNVD37HT46DA,False,1,
41,R2P7OUN7XCQTH1,B0C8VDSBP6,1.0 out of 5 stars Sounds good but DON'T GET I...,Howard Abraham,1,This speaker seemed like the perfect companion...,"Reviewed in the United States August 25, 2023",AF7AXIIL5CI7A6OLJMMNMCTJCDTA,False,3,
42,R1F1EUR5WVWO7P,B0C8VDSBP6,5.0 out of 5 stars Let’s Rock ‘n roll with it !,DavidLin,5,Small but rock ! Battery last longer than I th...,"Reviewed in the United States March 11, 2021",AEIPR4IRU7QJ24CIHBFENT3LPBDA,True,6,
43,R1UVRWH53HO4GW,B0C8VDSBP6,5.0 out of 5 stars Portable mini party,Rav4Squad,5,This little speaker is awesome.Nice rich sound...,"Reviewed in the United States March 17, 2021",AGSAQ2VJX5CDGXUKJJZUPBISZ3IA,True,2,
44,R2GNQHASRMVQR3,B0C8VDSBP6,"5.0 out of 5 stars Great sound, long life.",Deez reviews dawg..,5,"This speaker is amazing. It has two 4""subs. On...","Reviewed in the United States April 5, 2024",AHXPZTGN4NKWGBFOQOY6F7FZH3TQ,True,0,
45,R1L95DTVLL7D1M,B0C8VDSBP6,5.0 out of 5 stars Legit 🔊 LOUD!,Vanski,5,The media could not be loaded. You can't even ...,"Reviewed in the United States July 22, 2024",AGIUWCX3H3EOFKJJ4RRSK62TTF5Q,True,1,

In [86]:
df_1 = pd.read_csv('/content/reviews_1.csv')
df_2 = pd.read_csv('/content/reviews_2.csv')
df_3 = pd.read_csv('/content/reviews_3.csv')
df_4 = pd.read_csv('/content/reviews_4.csv')
df_5 = pd.read_csv('/content/reviews_5.csv')
df_6 = pd.read_csv('/content/reviews_6.csv')
df_7 = pd.read_csv('/content/reviews_7.csv')
df_8 = pd.read_csv('/content/reviews_8.csv')
df_9 = pd.read_csv('/content/reviews_9.csv')
df_10 = pd.read_csv('/content/reviews_10.csv')

df_1.head()

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R2SSSH04J4J264,B0D4STD5ZC,5.0 out of 5 stars Really nice portable speake...,Bruce C,5,Needed a new portable speaker for the home set...,"Reviewed in the United States July 1, 2024",AFVM53KRAU5JC462ZZDBBKTESPGA,True,9,Color: Statement RedStyle: PillPattern: Withou...
1,R39X7USU3OX34C,B0D4STD5ZC,5.0 out of 5 stars Really good,Justin,5,So I’m super picky about sound and have spent ...,"Reviewed in the United States July 8, 2024",AFSZPNTTLYCLNP536L6VS6UMFTNQ,True,2,Color: Statement RedStyle: PillPattern: Withou...
2,R4BQHA0TLLJNN,B0D4STD5ZC,5.0 out of 5 stars The best Speaker I have eve...,Leox,5,I really like the new Beats Pill 2024 speaker....,"Reviewed in the United States July 11, 2024",AEUCX7EIPTMCFN4OJBZHL2OYSVKQ,True,3,Color: Champagne GoldStyle: PillPattern: Witho...
3,R1BHCCLK5GZ5VZ,B0D4STD5ZC,5.0 out of 5 stars Beats Pill,Gregory Stratman,5,"I love the size, weight and quality of my Pill...","Reviewed in the United States August 2, 2024",AHCXUEC2FLLJ3S6F762OSBZJRDPA,True,0,Color: Matte BlackStyle: PillPattern: Without ...
4,R1ZHHB1YMHA1IF,B0D4STD5ZC,5.0 out of 5 stars Get a pair! You won’t regre...,I D Yelle,5,The Beats Pill (2024) has made a triumphant co...,"Reviewed in the United States June 29, 2024",AHO3EI5OGMXQFUMRJBH665YZXMBQ,True,22,Color: Matte BlackStyle: PillPattern: Without ...

In [88]:
merged_df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10], ignore_index=True)
merged_df

,review_id,product_id,title,author,rating,content,timestamp,profile_id,is_verified,helpful_count,product_attributes
0,R2SSSH04J4J264,B0D4STD5ZC,5.0 out of 5 stars Really nice portable speake...,Bruce C,5,Needed a new portable speaker for the home set...,"Reviewed in the United States July 1, 2024",AFVM53KRAU5JC462ZZDBBKTESPGA,True,9,Color: Statement RedStyle: PillPattern: Withou...
1,R39X7USU3OX34C,B0D4STD5ZC,5.0 out of 5 stars Really good,Justin,5,So I’m super picky about sound and have spent ...,"Reviewed in the United States July 8, 2024",AFSZPNTTLYCLNP536L6VS6UMFTNQ,True,2,Color: Statement RedStyle: PillPattern: Withou...
2,R4BQHA0TLLJNN,B0D4STD5ZC,5.0 out of 5 stars The best Speaker I have eve...,Leox,5,I really like the new Beats Pill 2024 speaker....,"Reviewed in the United States July 11, 2024",AEUCX7EIPTMCFN4OJBZHL2OYSVKQ,True,3,Color: Champagne GoldStyle: PillPattern: Witho...
3,R1BHCCLK5GZ5VZ,B0D4STD5ZC,5.0 out of 5 stars Beats Pill,Gregory Stratman,5,"I love the size, weight and quality of my Pill...","Reviewed in the United States August 2, 2024",AHCXUEC2FLLJ3S6F762OSBZJRDPA,True,0,Color: Matte BlackStyle: PillPattern: Without ...
4,R1ZHHB1YMHA1IF,B0D4STD5ZC,5.0 out of 5 stars Get a pair! You won’t regre...,I D Yelle,5,The Beats Pill (2024) has made a triumphant co...,"Reviewed in the United States June 29, 2024",AHO3EI5OGMXQFUMRJBH665YZXMBQ,True,22,Color: Matte BlackStyle: PillPattern: Without ...
...,...,...,...,...,...,...,...,...,...,...,...
413,R2P7OUN7XCQTH1,B0C8VDSBP6,1.0 out of 5 stars Sounds good but DON'T GET I...,Howard Abraham,1,This speaker seemed like the perfect companion...,"Reviewed in the United States August 25, 2023",AF7AXIIL5CI7A6OLJMMNMCTJCDTA,False,3,NaN
414,R1F1EUR5WVWO7P,B0C8VDSBP6,5.0 out of 5 stars Let’s Rock ‘n roll with it !,DavidLin,5,Small but rock ! Battery last longer than I th...,"Reviewed in the United States March 11, 2021",AEIPR4IRU7QJ24CIHBFENT3LPBDA,True,6,NaN
415,R1UVRWH53HO4GW,B0C8VDSBP6,5.0 out of 5 stars Portable mini party,Rav4Squad,5,This little speaker is awesome.Nice rich sound...,"Reviewed in the United States March 17, 2021",AGSAQ2VJX5CDGXUKJJZUPBISZ3IA,True,2,NaN
416,R2GNQHASRMVQR3,B0C8VDSBP6,"5.0 out of 5 stars Great sound, long life.",Deez reviews dawg..,5,"This speaker is amazing. It has two 4""subs. On...","Reviewed in the United States April 5, 2024",AHXPZTGN4NKWGBFOQOY6F7FZH3TQ,True,0,NaN
417,R1L95DTVLL7D1M,B0C8VDSBP6,5.0 out of 5 stars Legit 🔊 LOUD!,Vanski,5,The media could not be loaded. You can't even ...,"Reviewed in the United States July 22, 2024",AGIUWCX3H3EOFKJJ4RRSK62TTF5Q,True,1,NaN

In [94]:
merged_df.to_csv('merged_data.csv', index=False)

In [95]:
from google.colab import files

# Download the CSV file from Colab’s runtime
files.download(file_path)